### ISSUE TITLE
non functional..

### ISSUE THREAD

**Issue by TeoTwawki** [widgetbot-io/widgetbot#103]
The box the content should be in is empty, just the background color nothing else.

[video.zip](https://github.com/widgetbot-io/widgetbot/files/3180082/video.zip)

Pretty sure that shouldn't be what I see.

Have tried: 
- disabling all plugins.
- different browsers (chrome, firefox, seamonkey, edge, internet explorer, brave, opera..)
- different computer
- making sure javascript was enabled (it was)
- making sure anitivirus or other security software wasn't stopping it (no dice, not the cause)

As you can see in the attached video (zipped so github would accept the attachment, its only 60kb) this occurs even on your own site, proving I didn't just configure something wrong. No site I visit that is using widgetbot appears to have a working instance of any crate or embed that I see. And since I have tried multiple computers, it would have to be something all these computers have in common which as far as I can tell is only the sites being visited.

**Comment by advaith1** [comment]
Can you screenshot (or maybe describe) the issue? I can't download the zip rn

**Comment by TeoTwawki** [comment]
the box the content should be in is empty, just the background color nothing else.

**Comment by TeoTwawki** [comment]
![image](https://user-images.githubusercontent.com/6871475/57736404-cdf2bf80-7675-11e9-96fb-7bfec5792ce1.png)

**Comment by advaith1** [comment]
Any errors in the browser console? (Control shift j)

**Comment by TeoTwawki** [comment]
```
index.ts:75 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object.<anonymous> (https://disweb.deploys.io/channels/static/js/main.143bee95.js:1:683044)
    at n (https://disweb.deploys.io/channels/static/js/main.143bee95.js:1:110)
    at Object.<anonymous> (https://disweb.deploys.io/channels/static/js/main.143bee95.js:1:9556)
    at n (https://disweb.deploys.io/channels/static/js/main.143bee95.js:1:110)
    at Object.<anonymous> (https://disweb.deploys.io/channels/static/js/main.143bee95.js:1:672260)
    at n (https://disweb.deploys.io/channels/static/js/main.143bee95.js:1:110)
    at Object.<anonymous> (https://disweb.deploys.io/channels/static/js/main.143bee95.js:1:66521)
    at n (https://disweb.deploys.io/channels/static/js/main.143bee95.js:1:110)
    at Object.<anonymous> (https://disweb.deploys.io/channels/static/js/main.143bee95.js:1:599625)
    at n (https://disweb.deploys.io/channels/static/js/main.143bee95.js:1:110)
```

**Comment by advaith1** [comment]
You probably have "block third party cookies" or a similar setting enabled which is blocking WidgetBot

**Comment by TeoTwawki** [comment]
:man_facepalming: 

should probably let people know that is required in the documentation

**Comment by advaith1** [comment]
well its the default setting in pretty much all browsers, and also usually the site users wont look at the widgetbot documentation, only site admins will

but we do plan to show an error message when its blocking widgetbot #74

**Comment by TeoTwawki** [comment]
confirmed turd party cookie

(not a typo)

was about to click comment&close but you beat me to it on the closing part.
